### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by sayaanalam** [KuChainNetwork/Project-Deluge#2]
**Describe The Bug**
I Just Started hunting on your bug bounty program and came across a vulnerability that can cause a data leak.

Vulnerability - Credentials Exposure

**To Reproduce**

I just searched a query on your github respository and came across a database file exposed publically and it may cause a huge data loss.

File link - https://github.com/KuChainNetwork/kratos/blob/5c056369a6a0e95c5976fe93bfe6bd9a4c5c4cf2/scripts/configs/plugins.json

Visit the above link and you'll notice that db credentials are being leaked there....

**Expected Behavior**

Those credentials should not be there

**Contact Information**

Email - alamsayaan98@gmail.com

Sayaan Alam

**Comment by Pisces-Anjou** [comment]
**Hi Sayaan:**



Thanks for your submission.

The configuration file you mentioned(kratos/scripts/configs/plugins.json) is just a sample template with no real meaning, it is here to show the developers how to configure the DB file. The DB file stores block data which is public. The description of this configuration file is not rigorous, and we will pay more attention to this in the future. However, it will not cause any user data leak. 

In summary, this vulnerability report is not valid.

Thanks for your attention again! Please keep trying and help us improve our chain.



**Regards**

**KuChain Team**
