### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mahmoud422** [KuChainNetwork/Project-Deluge#5]
There is an error this file should be hidden or encrypted. This file may cause users to leak information. Also, there is a loophole in it by making a script to guess users with the help of the API. This file must be encrypted. 
This file https://github.com/KuChainNetwork/kratos/blob/5c056369a6a0e95c5976fe93bfe6bd9a4c5c4cf2/scripts/configs/plugins.json
 Thank you. I wish you a good day.

**Comment by Pisces-Anjou** [comment]
Hi,



Thanks for your submission.

Please read the rules carefully before submitting report. Vulnerability report which doesn't follow the report template will be considered invalid.

What's more, the issue you mentioned has been reported before. It is an invalid issue. Please check it [here](https://github.com/KuChainNetwork/Project-Deluge/issues/2). 

Thanks for your attention! Please keep trying and help us improve our chain.



**Regards**

**KuChain Team**
